FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .

# instalar dependências de build para compilar psycopg2, instalar deps python e então remover build deps
RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential libpq-dev python3-dev && \
    pip install --no-cache-dir -r requirements.txt && \
    apt-get remove -y --purge build-essential python3-dev libpq-dev && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

COPY . .

ENV PYTHONUNBUFFERED=1
EXPOSE 8000

# modo dev com reload
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]