FROM python:3.13-alpine

WORKDIR /app

COPY requirements.txt .

# instalar dependências de build e runtime para psycopg2
RUN apk add --no-cache --virtual .build-deps \
      build-base \
      postgresql-dev \
      python3-dev \
      linux-headers && \
    apk add --no-cache libpq && \
    pip install --no-cache-dir -r requirements.txt && \
    apk del .build-deps

COPY . .

ENV PYTHONUNBUFFERED=1

EXPOSE 8000

# modo dev com reload
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]